---
title: "Food Insecurity in Mozambique and Tanzania" 
author: "Amy Mitchell-Whittington"
date: 2023-06-13
categories: ["Tidy Tuesday"]
tags: ["TidyTuesday"]
image:
  caption: ''
  focal_point: ''
  preview_only: no
summary: Getting back into the swing of things with a dataset from the Studying African Farmer-Led Irrigation (SAFI) project team.
---

## SAFI Survey [</>](https://github.com/amymitchell-whittington/TidyTuesday/blob/main/2023/13-06-2023-safidata/13-06-2023-safidata.Rmd)  

This week's Tidy Tuesday data comes from the [SAFI (Studying African Farmer-Led Irrigation) project team](http://www.safi-research.org/). The aim of SAFI is to better understand farming and small-scale irrigation methods used in rural areas of Africa to see if these methods can "offer a model for broad-based economic growth". 

Between 2016 and 2017, SAFI sent out a survey to households in Tanzania and Mozambique to learn more about each household (e.g., number of rooms and household members, type of home) and their agricultural practices (e.g., water usage, number of livestock).

It took me a little time to get back into the swing of things, given this was my first week back on the tools since 2021, so I kept it straightforward. I focused on a question in the survey where households were asked to "indicate which months, In the last 12 months have you faced a situation when you did not have enough food to feed the household?". I found that across Tanzania and Mozambique, almost 75% of respondents said they'd had to go through at least one month without enough food for their household. 

After some initial reading, I found that households in both  [Mozambique](https://www.climatelinks.org/sites/default/files/asset/document/mozambique_climate_vulnerability_profile_jan2013.pdf) and [Tanzania](https://wwfeu.awsassets.panda.org/downloads/east_africa_climate_change_impacts_final_2.pdf) depend heavily on rain-fed agriculture, which can make livelihood and food security vulnerable to climate change. If I had of had more time, I would have liked to pair my chart with precipitation data for the same period - and provide yearly averages - to see whether there was any correlation, but I ran out of time on this one!

```{r plot, echo=FALSE, include=FALSE, dpi=300}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(ggtext)

safi_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-13/safi_data.csv')

summary(safi_data)

#separate "months_lack_food" column by ";", group by the month and find how many households lacked enough food in each month across the three villages.
df <- safi_data %>%
  separate_rows(months_lack_food, sep = ";") %>%
  mutate(months_lack_food = gsub("July", "Jul", months_lack_food)) %>%
  mutate(months_lack_food = gsub("June", "Jun", months_lack_food)) %>%
  mutate(months_lack_food = gsub("Sept", "Sep", months_lack_food)) %>%
  #mutate(season = ifelse(months_lack_food %in% c("Jan", "Feb", "Mar", "Oct", "Nov", "Dec"), "Hot and Humid Season", "Cool and Dry Season")) %>%
  group_by(months_lack_food, village) %>%
  summarise(count = n()) %>%
  filter(months_lack_food != "none")

#plot
df %>% 
  ggplot(aes(x = months_lack_food, y = count, fill = village)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(limits = month.abb) +
  scale_y_continuous(breaks = c(seq(from = 0, to = 40, by = 2))) +
  theme_classic() +
  theme(plot.title = element_markdown(size = 13, face = "bold"),
        plot.subtitle = element_text(size = 7),
        plot.caption = element_text(size = 6, face = "italic"),
        panel.background = element_rect(fill = "ivory"),
        plot.background = element_rect(fill = "ivory2"),
        legend.background = element_rect(fill = "ivory2"),
         panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1, color="ivory3")) +
  scale_fill_manual(values = c("blue4", "green4", "orange")) +
  labs(title = "Food insecurity in Mozambique and Tanzania",
       subtitle = "Between 2016-2017, 131 households from three villages across Mozambique and Tanzania were asked about their living conditions\nas part of a survey run by the Studying African Farmer-Led Irrigation group. Almost three quarters of respondents said\nthey'd faced at least one month of not having enough food to feed their household in the previous year.",
       caption = "Data source: SAFI (Studying African Farmer-Led Irrigation) survey.",
       x = "Month",
       y = "Number of households without enough food",
       fill = "Villages")
```